In [1]:
import xarray as xr

In [2]:
filename = "composite_conus_2023086.nc"

In [4]:
ds = xr.open_dataset(filename)

In [5]:
ds

<xarray.Dataset>
Dimensions:                         (ny: 1319, nx: 2079)
Dimensions without coordinates: ny, nx
Data variables:
    Times                           (ny, nx) |S19 ...
    latitude                        (ny, nx) float32 ...
    longitude                       (ny, nx) float32 ...
    10h_dead_fuel_moisture_content  (ny, nx) float32 ...

In [8]:
times = ds.Times.values

In [9]:
type(times)

numpy.ndarray

In [10]:
times.shape

(1319, 2079)

In [11]:
times[0,0]

b'0000-01-01_00:00:00'

In [14]:
type(times[0,0])

numpy.bytes_

In [19]:
ds2 = xr.open_dataset("conus_2023086.nc")

In [20]:
ds2

<xarray.Dataset>
Dimensions:                         (ny: 1319, nx: 2079)
Dimensions without coordinates: ny, nx
Data variables:
    Times                           (ny, nx) |S19 ...
    latitude                        (ny, nx) float32 ...
    longitude                       (ny, nx) float32 ...
    10h_dead_fuel_moisture_content  (ny, nx) float32 ...

In [22]:
ds2.Times.values == ds.Times.values

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])

In [26]:
ds2.Times.values[1318, 2078]

b'0000-01-01_00:00:00'

In [27]:
ds2.Times.values[0, 0]

b'0000-01-01_00:00:00'

In [28]:
ds.Times.values[1318, 2078]

b'2023-03-22_18:00:00'

In [29]:
ds.Times.values[0, 0]

b'0000-01-01_00:00:00'

In [37]:
ds['10h_dead_fuel_moisture_content'].values

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [       nan,        nan,        nan, ..., 14.211778 , 14.168687 ,
        14.017469 ],
       [       nan,        nan,        nan, ..., 14.99362  , 15.435079 ,
        15.474676 ],
       [       nan,        nan,        nan, ..., 16.310316 , 13.9080105,
        14.950796 ]], dtype=float32)

In [38]:
ds2['10h_dead_fuel_moisture_content'].values

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)