In [1]:
from moisture_rnn import staircase, staircase_2
import numpy as np

2023-12-27 23:43:03.982609: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# training data shape   [batch_size, sequence_length, features] 
# also called           [samples,timesteps,features]
# input data size       [trainsteps,features] 

In [3]:
trainsteps=100
timesteps=5
features=1
outputs=1
x=np.tile(range(trainsteps), (features, 1)).T
y=np.tile(range(trainsteps), (outputs, 1)).T
# print('x =',x)
print('x shape =',x.shape)
# print('y =',y)
print('y shape =',y.shape)


x shape = (100, 1)
y shape = (100, 1)


In [4]:
x_train, y_train = staircase(x,y,timesteps,trainsteps,return_sequences=False, verbose = True)
print('x_train shape =',x_train.shape)
print('y_train shape =',y_train.shape)
print('x_train =',x_train)
print('y_train =',y_train)


shape x =  (100, 1)
shape y =  (100, 1)
timesteps= 5
trainsteps= 100
staircase: samples= 96 timesteps= 5 features= 1
return_sequences= False
returning only the last timestep in a sample
x_train shape = (96, 5, 1)
y_train shape = (96, 1)
x_train = [[[ 0.]
  [ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]
  [ 5.]]

 [[ 2.]
  [ 3.]
  [ 4.]
  [ 5.]
  [ 6.]]

 [[ 3.]
  [ 4.]
  [ 5.]
  [ 6.]
  [ 7.]]

 [[ 4.]
  [ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]
  [ 9.]]

 [[ 6.]
  [ 7.]
  [ 8.]
  [ 9.]
  [10.]]

 [[ 7.]
  [ 8.]
  [ 9.]
  [10.]
  [11.]]

 [[ 8.]
  [ 9.]
  [10.]
  [11.]
  [12.]]

 [[ 9.]
  [10.]
  [11.]
  [12.]
  [13.]]

 [[10.]
  [11.]
  [12.]
  [13.]
  [14.]]

 [[11.]
  [12.]
  [13.]
  [14.]
  [15.]]

 [[12.]
  [13.]
  [14.]
  [15.]
  [16.]]

 [[13.]
  [14.]
  [15.]
  [16.]
  [17.]]

 [[14.]
  [15.]
  [16.]
  [17.]
  [18.]]

 [[15.]
  [16.]
  [17.]
  [18.]
  [19.]]

 [[16.]
  [17.]
  [18.]
  [19.]
  [20.]]

 [[17.]
  [18.]
  [19.]
  [20.]
  [21.]

In [5]:
x_train, y_train = staircase_2(x,y,timesteps,return_sequences=False, verbose = True)
print('x_train shape =',x_train.shape)
print('y_train shape =',y_train.shape)
#print('x_train =',x_train)
#print('y_train =',y_train)
for i in range(x_train.shape[0]):
    print('x_train[',i,']:')
    print(x_train[i])

shape x =  (100, 1)
shape y =  (100, 1)
timesteps= 5
return_sequences= False
batch 0 sequence 0 data items 0 to 4
batch 0 sequence 1 data items 1 to 5
batch 0 sequence 2 data items 2 to 6
batch 0 sequence 3 data items 3 to 7
batch 0 sequence 4 data items 4 to 8
batch 1 sequence 0 data items 5 to 9
batch 1 sequence 1 data items 6 to 10
batch 1 sequence 2 data items 7 to 11
batch 1 sequence 3 data items 8 to 12
batch 1 sequence 4 data items 9 to 13
batch 2 sequence 0 data items 10 to 14
batch 2 sequence 1 data items 11 to 15
batch 2 sequence 2 data items 12 to 16
batch 2 sequence 3 data items 13 to 17
batch 2 sequence 4 data items 14 to 18
batch 3 sequence 0 data items 15 to 19
batch 3 sequence 1 data items 16 to 20
batch 3 sequence 2 data items 17 to 21
batch 3 sequence 3 data items 18 to 22
batch 3 sequence 4 data items 19 to 23
batch 4 sequence 0 data items 20 to 24
batch 4 sequence 1 data items 21 to 25
batch 4 sequence 2 data items 22 to 26
batch 4 sequence 3 data items 23 to 27
bat